---
- import_playbook: playbooks/os_setup.yaml
- import_playbook: playbooks/nvidia_setup.yaml
- import_playbook: playbooks/docker_setup.yaml
- import_playbook: playbooks/triton_deploy.yaml
- import_playbook: playbooks/verify.yaml
